#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_front:
  path: /app
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'app_front.html.twig'